"""#26 VC export helpers — structure & status layer tests.

Bitstring decoding is pinned with a fixed cross-language vector: the string
below was produced by the Node signer stack (zlib gzipSync + base64url) and
is asserted byte-for-byte here — apps/api-sg/src/vc-status-list.test.ts pins
the same vector, guaranteeing signer(Node) → verifier(Python) interop.
"""

from __future__ import annotations

import gzip
import base64
import json

import pytest

from jiaozi_gdid import (
    VcExportError,
    build_status_payload,
    check_bitstring_entry,
    check_vc_status,
    credential_status_entries,
    decode_status_list_bitstring,
    fetch_vc,
    generate_ed25519_keypair,
    sign_status_payload,
    status_list_bit,
    validate_vc_structure,
)

CORE = "https://core.test"

# bits {0, 1, 4000, 131071} set in a 131,072-bit (16KB) list — generated by
# the Node encoder; same constant lives in vc-status-list.test.ts
FIXED_VECTOR = (
    "uH4sIAAAAAAAACu3OMQEAAAQAMJqLJppfAYctwTr4pq4DAAAAAAAAAAAAAAAAAAAAbDkt82tcAEAAAA"
)
FIXED_VECTOR_SET_BITS = [0, 1, 4000, 131071]


def encode_bitstring(bits: bytes) -> str:
    """Local reference encoder (mirrors the Node side) for roundtrip tests."""
    return "u" + base64.urlsafe_b64encode(gzip.compress(bits, mtime=0)).decode().rstrip("=")


def make_bits(set_indexes: list[int], size_bytes: int = 16384) -> bytes:
    buf = bytearray(size_bytes)
    for i in set_indexes:
        buf[i >> 3] |= 0x80 >> (i & 7)
    return bytes(buf)


class FakeResponse:
    def __init__(self, body, status_code: int = 200):
        self._body = body
        self.status_code = status_code

    def json(self):
        return json.loads(json.dumps(self._body))


class FakeClient:
    """Maps URL → response; records requests."""

    def __init__(self, routes: dict):
        self.routes = routes
        self.requested: list[str] = []

    def get(self, url: str) -> FakeResponse:
        self.requested.append(url)
        if url not in self.routes:
            return FakeResponse({"error": "not_found"}, 404)
        body = self.routes[url]
        if isinstance(body, FakeResponse):
            return body
        return FakeResponse(body)


def sample_vc(cert_id: str = "JIAOZI-2026-000123") -> dict:
    return {
        "@context": [
            "https://www.w3.org/ns/credentials/v2",
            "https://www.jiaozi.io/ns/attest/v1.json",
        ],
        "id": f"{CORE}/api/certs/{cert_id}/vc",
        "type": ["VerifiableCredential", "JiaoziAttestationCredential"],
        "issuer": "did:web:core.test",
        "validFrom": "2026-08-24T00:00:00.000Z",
        "credentialSubject": {
            "id": f"did:web:core.test:agents:{cert_id.lower()}",
            "type": "JiaoziAgentAttestation",
            "agentName": "sample-agent",
            "trustLevel": "software",
        },
        "credentialStatus": [
            {
                "type": "BitstringStatusListEntry",
                "statusPurpose": "revocation",
                "statusListIndex": "123",
                "statusListCredential": f"{CORE}/api/status-list/revocation",
            },
            {
                "id": f"{CORE}/api/status/{cert_id}",
                "type": "JiaoziStatusV1Entry",
                "statusPurpose": "revocation",
            },
        ],
        "proof": {
            "type": "DataIntegrityProof",
            "cryptosuite": "eddsa-rdfc-2022",
            "created": "2026-08-24T00:00:00Z",
            "verificationMethod": "did:web:core.test#z6MkExample",
            "proofPurpose": "assertionMethod",
            "proofValue": "z5ExampleProofValue",
        },
    }


def status_list_credential(set_indexes: list[int], purpose: str = "revocation") -> dict:
    return {
        "@context": ["https://www.w3.org/ns/credentials/v2"],
        "id": f"{CORE}/api/status-list/revocation",
        "type": ["VerifiableCredential", "BitstringStatusListCredential"],
        "issuer": "did:web:core.test",
        "validFrom": "2026-08-24T00:00:00.000Z",
        "validUntil": "2026-08-24T00:15:00.000Z",
        "credentialSubject": {
            "id": f"{CORE}/api/status-list/revocation#list",
            "type": "BitstringStatusList",
            "statusPurpose": purpose,
            "encodedList": encode_bitstring(make_bits(set_indexes)),
        },
    }


class TestBitstringDecoding:
    def test_fixed_cross_language_vector(self):
        bits = decode_status_list_bitstring(FIXED_VECTOR)
        assert len(bits) == 16384  # 131,072 bits = spec minimum
        set_bits = [i for i in range(len(bits) * 8) if status_list_bit(bits, i)]
        assert set_bits == FIXED_VECTOR_SET_BITS

    def test_msb_first_bit_order(self):
        bits = bytes([0b1100_0000, 0b1000_0001])
        assert status_list_bit(bits, 0) is True
        assert status_list_bit(bits, 1) is True
        assert status_list_bit(bits, 2) is False
        assert status_list_bit(bits, 8) is True
        assert status_list_bit(bits, 15) is True
        assert status_list_bit(bits, 14) is False

    def test_out_of_range_index_fails_closed(self):
        bits = bytes(2)
        with pytest.raises(ValueError):
            status_list_bit(bits, 16)
        with pytest.raises(ValueError):
            status_list_bit(bits, -1)

    def test_rejects_missing_multibase_prefix(self):
        with pytest.raises(ValueError):
            decode_status_list_bitstring(FIXED_VECTOR[1:])

    def test_roundtrip_with_local_encoder(self):
        original = make_bits([7, 8, 94567])
        assert decode_status_list_bitstring(encode_bitstring(original)) == original


class TestStructureValidation:
    def test_valid_export_passes(self):
        assert validate_vc_structure(sample_vc()) == []

    def test_single_status_object_also_accepted(self):
        vc = sample_vc()
        vc["credentialStatus"] = vc["credentialStatus"][1]  # object, not array
        assert validate_vc_structure(vc) == []
        assert len(credential_status_entries(vc)) == 1

    def test_problems_reported(self):
        vc = sample_vc()
        vc["proof"] = [vc["proof"]]  # proof set → 导出层不符(实测坑 2)
        vc["type"] = ["VerifiableCredential"]
        del vc["credentialStatus"]
        problems = validate_vc_structure(vc)
        assert any("proof must be a single object" in p for p in problems)
        assert any("JiaoziAttestationCredential" in p for p in problems)
        assert any("credentialStatus missing" in p for p in problems)

    def test_wrong_cryptosuite_reported(self):
        vc = sample_vc()
        vc["proof"]["cryptosuite"] = "eddsa-jcs-2022"
        assert any("eddsa-rdfc-2022" in p for p in validate_vc_structure(vc))

    def test_bad_bitstring_entry_reported(self):
        vc = sample_vc()
        vc["credentialStatus"][0]["statusListIndex"] = 123  # 规范要求字符串
        assert any("digit string" in p for p in validate_vc_structure(vc))


class TestBitstringEntryCheck:
    def entry(self, index: str = "123") -> dict:
        return {
            "type": "BitstringStatusListEntry",
            "statusPurpose": "revocation",
            "statusListIndex": index,
            "statusListCredential": f"{CORE}/api/status-list/revocation",
        }

    def test_bit_clear_and_set(self):
        client = FakeClient(
            {f"{CORE}/api/status-list/revocation": status_list_credential([7, 456])}
        )
        clear = check_bitstring_entry(self.entry("123"), client=client)
        assert clear["set"] is False
        assert clear["statusPurpose"] == "revocation"
        assert clear["listValidUntil"] == "2026-08-24T00:15:00.000Z"
        assert check_bitstring_entry(self.entry("456"), client=client)["set"] is True

    def test_purpose_mismatch_fails_closed(self):
        client = FakeClient(
            {f"{CORE}/api/status-list/revocation": status_list_credential([], "suspension")}
        )
        with pytest.raises(ValueError, match="statusPurpose mismatch"):
            check_bitstring_entry(self.entry(), client=client)

    def test_unavailable_list_raises(self):
        client = FakeClient({})
        with pytest.raises(VcExportError):
            check_bitstring_entry(self.entry(), client=client)


class TestCombinedStatusAndFetch:
    issuer = generate_ed25519_keypair()

    def signed_status(self, cert_id: str, status: str) -> dict:
        payload = build_status_payload(
            cert_id=cert_id,
            did=f"did:web:core.test:agents:{cert_id.lower()}",
            status=status,
            trust_level="revoked" if status == "revoked" else "software",
            issuer="sg-core",
            ttl_seconds=60,
        )
        return sign_status_payload(
            payload, self.issuer["privateKeyPkcs8Base64"], self.issuer["publicKeyMultibase"]
        )

    def test_active_on_both_channels(self):
        vc = sample_vc()
        client = FakeClient(
            {
                f"{CORE}/api/status/JIAOZI-2026-000123": self.signed_status(
                    "JIAOZI-2026-000123", "active"
                ),
                f"{CORE}/api/status-list/revocation": status_list_credential([7]),
            }
        )
        result = check_vc_status(vc, client=client)
        assert result["revoked"] is False
        assert result["status"] == "active"
        assert result["sources"]["jiaoziStatusV1"]["valid"] is True
        assert result["sources"]["bitstringStatusList"]["set"] is False

    def test_revoked_on_either_channel_wins(self):
        vc = sample_vc()
        # 仅位图通道置位(status.v1 尚在 active 窗口)→ 仍判 revoked(取更严一方)
        client = FakeClient(
            {
                f"{CORE}/api/status/JIAOZI-2026-000123": self.signed_status(
                    "JIAOZI-2026-000123", "active"
                ),
                f"{CORE}/api/status-list/revocation": status_list_credential([123]),
            }
        )
        result = check_vc_status(vc, client=client)
        assert result["revoked"] is True
        assert result["status"] == "revoked"

        # 仅 status.v1 判吊销(位图未及重签)→ 同样 revoked
        client2 = FakeClient(
            {
                f"{CORE}/api/status/JIAOZI-2026-000123": self.signed_status(
                    "JIAOZI-2026-000123", "revoked"
                ),
                f"{CORE}/api/status-list/revocation": status_list_credential([]),
            }
        )
        result2 = check_vc_status(vc, client=client2)
        assert result2["revoked"] is True
        assert result2["status"] == "revoked"

    def test_channel_failures_are_reported_not_swallowed(self):
        vc = sample_vc()
        client = FakeClient({})  # 两个通道都 404
        result = check_vc_status(vc, client=client)
        assert result["revoked"] is False
        assert result["status"] == "unknown"
        assert "error" in result["sources"]["bitstringStatusList"]
        # status.v1 端点 404 返回的 JSON 不是合法凭证 → bad_shape
        assert result["sources"]["jiaoziStatusV1"] == {"valid": False, "reason": "bad_shape"}

    def test_fetch_vc_ok_and_error(self):
        vc = sample_vc()
        client = FakeClient(
            {
                f"{CORE}/api/certs/JIAOZI-2026-000123/vc": vc,
                f"{CORE}/api/certs/JIAOZI-2026-000999/vc": FakeResponse(
                    {"error": "credential_revoked"}, 410
                ),
            }
        )
        fetched = fetch_vc("JIAOZI-2026-000123", core_url=CORE, client=client)
        assert fetched["id"] == vc["id"]
        with pytest.raises(VcExportError) as exc_info:
            fetch_vc("JIAOZI-2026-000999", core_url=CORE, client=client)
        assert exc_info.value.status_code == 410
        assert exc_info.value.body["error"] == "credential_revoked"
